# Copyright (c) 2026 Orange. All rights reserved.
# This software is distributed under the MIT License, the text of which is available
# at https://spdx.org/licenses/MIT.html or see the "LICENSE" file for more details.

"""Optimized Univariate Encoding

This module contains everything needed to make univariate variable transformation
optimized through the use of the C++ implementation of 'umodl'. It calls the
'umodl' executable as a subprocess indirectly by the use the 'umodl' library.

The main class of this module is 'OptimizedUnivariateEncoding'.

An example code is in examples/optimized_univariate_encoding.py.
"""

import pathlib
import tempfile
from warnings import warn
import json
from typing import Union
from itertools import starmap
import khiops.sklearn.dataset
import pandas as pd
from umodl import run_umodl
from .helperclasses import ValGrp, ValGrpPartition, Interval, IntervalPartition, TargetTreatmentPair


class OptimizedUnivariateEncoding:
    """
    The OptimizedUnivariateEncoding class makes use of the external umodl tool hosted at https://github.com/UData-Orange/umodl.

    Attributes
    ----------
    model: dict mapping str to ValGrpPartition or IntervalPartition
        The model generated by the 'umodl' executable.
        It describes the partitioning of values of informative variables into groups or intervals.
        It maps the informative variable names to value partitions.

    levels: list of (str, float) pairs
        (variable-name, variable-level) pairs in decreasing level order.

    variable_cols: DataFrame
        The data columns of all variables.
        This means all the data from the dataset but the treatment and target columns.

    treatment_col: Series
        The treatment column from the dataset.

    target_col: Series
        The target column from the dataset.

    treatment_groups: dict mapping str to dict mapping ValGrp or Interval to int
        The keys are the variable names. The values are themselves dictionaries, which keys are ValGrp
        or Interval and which values are numbers.
    """

    def __init__(self):
        self.model: dict[str, Union[ValGrpPartition, IntervalPartition]] = {}
        self.levels: list[tuple[str, float]] = []
        self.variable_cols = None
        self.treatment_col = None
        self.target_col = None
        self.treatment_groups = None

    @property
    def input_variables(self):
        """list of str
        
        The names of the variables.
        """
        return self.variable_cols.columns.to_list()
    
    @property
    def informative_input_variables(self):
        """list of str
        
        The names of the informative variables.
        """
        return [v for v in self.input_variables if v in self.model]
    
    @property
    def noninformative_input_variables(self):
        """list of str
        
        The names of the non-informative variables.
        """
        return [v for v in self.input_variables if v not in self.model]
    
    @property
    def treatment_name(self):
        """str
        
        The name of the treatment column.
        """
        return self.treatment_col.name
    
    @property
    def target_name(self):
        """str
        
        The name of the target column.
        """
        return self.target_col.name
    
    @property
    def treatment_modalities(self):
        """list
        
        All the different treatments from the dataset.
        """
        return sorted(self.treatment_col.unique())
    
    @property
    def target_modalities(self):
        """list
        
        All the different targets from the dataset.
        """
        return sorted(self.target_col.unique())
    
    @property
    def target_treatment_pairs(self):
        """list of TargetTreatmentPair
        
        All (target, treatment) pairs.
        """
        return [TargetTreatmentPair(target, treatment) for target in self.target_modalities for treatment in self.treatment_modalities]

    def fit_transform(self, data, treatment_col, target_col, maxparts = None):
        """Learn a discretisation model using UMODL and transform the data.

        Parameters
        ----------
        data: pd.DataFrame
            Dataframe containing feature variables. Categorical
            variables should have the object dtype, otherwise they
            are processed as numerical variables.
        treatment_col: pd.Series
            Treatment column.
        target_col: pd.Series
            Outcome column.
        maxparts: int, default=None
            The maximal number of intervals or groups. None means default to the 'umodl' program default.

        Returns
        -------
        pd.Dataframe
            Pandas Dataframe that contains encoded data.
        """
        self.fit(data, treatment_col, target_col, maxparts)
        return self.transform(data)
    
    def fit(self, data, treatment_col, target_col, maxparts = None):
        """Learn a discretisation model using UMODL.

        Parameters
        ----------
        data: pd.DataFrame
            Dataframe containing feature variables. Categorical
            variables should have the object dtype, otherwise they
            are processed as numerical variables.
        treatment_col: pd.Series
            Treatment column.
        target_col: pd.Series
            Outcome column.
        maxparts: int, default=None
            The maximal number of intervals or groups. None means default to the 'umodl' program default.
        """
        # Force the types of the treatment and target columns so that khiops lib understands they are categorical
        if treatment_col.dtype != object:
            warn("Treatment column's dtype is not object; fixing...")
            treatment_col = treatment_col.astype(object)
        if target_col.dtype != object:
            warn("Target column's dtype is not object; fixing...")
            target_col = target_col.astype(object)

        # Create temporary .txt (data) and .kdic (Khiops dictionary) files for use with the umodl executable
        with tempfile.TemporaryDirectory() as dirname:
            dirpath = pathlib.Path(dirname)
            kdicfilename = str(dirpath / "main_table.kdic")
            dataset = khiops.sklearn.dataset.Dataset(data.join([treatment_col, target_col]))

            txtfilename, _ = dataset.create_table_files_for_khiops(dirname)  # Create .txt file
            dataset.create_khiops_dictionary_domain().export_khiops_dictionary_file(kdicfilename)  # Create .kdic file
            run_umodl(txtfilename, kdicfilename, "main_table", treatment_col.name, target_col.name, maxparts)

            txtfilepath = pathlib.Path(txtfilename)
            with open(txtfilepath.with_name(f"UP_{txtfilepath.stem}.json")) as jsonfile:
                docroot = json.load(jsonfile)

        model = {}
        treatment_groups = {}
        for variable in docroot['detailed statistics']:
            vardim = variable['dataGrid']['dimensions'][0]
            varname = vardim['variable']
            if vardim['partitionType'] == 'Value groups':
                model[varname] = ValGrpPartition(list(map(ValGrp, vardim['partition'])), vardim['defaultGroupIndex'])
            elif vardim['partitionType'] == 'Intervals':
                model[varname] = IntervalPartition(list(starmap(Interval, vardim['partition'])))
            else: raise ValueError("unsupported partition type")
            treatment_groups[varname] = dict(zip(model[varname], variable.get('Treatement Groups', [])))

        levels = sorted(
            ((attr['name'], attr['level']) for attr in docroot['attributes']),
            key=lambda namelevel: (-namelevel[1], namelevel[0])
        )

        # Only write to the instance's attributes if all the above succeeded.
        self.model = model
        self.levels = levels
        self.variable_cols = data
        self.treatment_col = treatment_col
        self.target_col = target_col
        self.treatment_groups = treatment_groups


    def transform(self, data):
        """Apply the discretisation model learned by the fit() method.

        Parameters
        ----------
        data: pd.DataFrame
            Dataframe containing feature variables.

        Returns
        -------
        pd.DataFrame
            Pandas Dataframe that contains encoded data.
        """
        data = data[list(self.model.keys())]  # Keep only informative variables
        self.transformed_data = data.transform(lambda col: self.model[col.name].transform(col))
        return self.transformed_data
    
    def get_levels(self):
        """Get the level of all variables.
        
        Returns
        -------
        list[tuple[str, float]]
            (variable-name, variable-level) pairs in decreasing level order.
        """
        return self.levels
    
    def get_level(self, variable):
        """Get the level of a single variable.

        Parameters
        ----------
        variable: str
            The variable to get the level from.
        
        Returns
        -------
        float
            The level of the specified variable.
        """
        return dict(self.levels)[variable]
    
    def get_partition(self, variable):
        """Get the partition corresponding to a single variable of the model.

        Parameters
        ----------
        variable: str
            The variable name.
        
        Returns
        -------
        ValGrpPartition | IntervalPartition
            The partition corresponding to a single variable of the model.
        """
        return self.model[variable]
    
    def get_target_frequencies(self, variable):
        """Get the frequencies for each (target, treatment) pair.
        
        The frequencies are computed for a single variable.
        
        Parameters
        ----------
        variable: str
            The variable name.

        Returns
        -------
        pd.DataFrame
            The frequencies as a Dataframe containing:
                - A column named 'Part' listing all the parts of the variable.
                - One column per (target, treatment) pair.
        """
        varcol = self.variable_cols[variable]
        partition = self.get_partition(variable)
        return pd.DataFrame(
            {
                **{"Part": partition},
                **{
                    ttpair: [
                        len(
                            varcol[
                                (self.treatment_col == ttpair.treatment) & (self.target_col == ttpair.target) & varcol.map(lambda elem: partition.transform_elem(elem) == i)
                            ]
                        )
                        for i, _ in enumerate(partition)
                    ]
                    for ttpair in self.target_treatment_pairs
                }
            }
        )
    
    def get_target_probabilities(self, variable):
        """Get the probabilities P(target|treatment) for each (target, treatment) pair.
        
        The probabilities are computed for a single variable.
        
        Parameters
        ----------
        variable: str
            The variable name.

        Returns
        -------
        pd.DataFrame
            The probabilities as a Dataframe containing:
                - A column named 'Part' listing all the parts of the variable.
                - One column per (target, treatment) pair.
        """
        freqs = self.get_target_frequencies(variable)
        return freqs["Part"].to_frame().join(
            pd.DataFrame({
                ttpair: [
                    freqs[ttpair][freqs["Part"] == part].sum() / freqs[
                        [TargetTreatmentPair(target, ttpair.treatment) for target in self.target_modalities]
                    ][freqs["Part"] == part].sum().sum()
                    for part in self.get_partition(variable)
                ]
                for ttpair in self.target_treatment_pairs
            })
        )

    
    def get_uplift(self, reftarget, reftreatment, variable):
        """Get the uplift for a single variable.

        See explanations of the computations in the 'Returns' section below.
        
        Parameters
        ----------
        reftarget
            The reference target.
        reftreatment
            The reference treatment to which all the other treatments are compared.
        variable: str
            The name of the variable.

        Returns
        -------
        pd.DataFrame
            A Dataframe containing:
                - A column named 'Part' listing all the parts of the variable.
                - One column per treatment other than the reference treatment.
                  A column gives the difference P(reftarget|treatment) - P(reftarget|reftreatment), that is,
                  the benefit (or deficit) of probabilities to have 'reftarget' as the outcome with the column's
                  treatment compared to the reference treatment.
        """
        probs = self.get_target_probabilities(variable)
        refprobs = probs[TargetTreatmentPair(reftarget, reftreatment)]
        return probs["Part"].to_frame().join(pd.DataFrame({
            f"Uplift {reftarget} {treatment}": probs[TargetTreatmentPair(reftarget, treatment)] - refprobs
            for treatment in self.treatment_modalities if treatment != reftreatment
        }))
